### ISSUE TITLE
custom drawer2

### ISSUE THREAD

**Issue by Torstentjh** [Rakha112/react-native-animation#2]
hello，I am a newbie in react native. I watched your video tutorial of drawer and encountered a problem. I used the react native navigation library and nested the home page into the bottom-tab navigation. Then I followed your video and it only reduced the size of this component, not the entire content of the screen. I read the documentation of this library but didn't find a solution. Do you have a good solution? 😭

**Comment by Rakha112** [comment]
Hey @Torstentjh, could you send a screenshot of the error you're experiencing or create a repro on Expo Snack or a GitHub repo ?

**Comment by Torstentjh** [comment]
> Hey @Torstentjh, could you send a screenshot of the error you're experiencing or create a repro on Expo Snack or a GitHub repo ?

thanks a lot ，Actually, this is not an error. My homepage is displayed as a routed interface. The implementation of the react native navigation library caused this problem, so I set the bottom Tabbar height to 0 when I click it. It looks similar. Although this is stupid, it can meet my needs. I don’t need to solve this problem for the time being. Thank you
![image](https://github.com/Rakha112/react-native-animation/assets/75771172/ad44e4b5-a0b4-435c-aa56-b71e7e470afe)
like this，i set height when i click and show drawer，it works ，although it stupid🤣

**Comment by Rakha112** [comment]
Hey, I'm really sorry for my late response. Is this the bug you're experiencing when using nested navigators with bottom tabs ?

https://github.com/Rakha112/react-native-animation/assets/61527649/e81c114b-f18f-4f12-9ec7-d60401356a9e

If so, you can move the Drawer to your BottomTabsNavigator


https://github.com/Rakha112/react-native-animation/assets/61527649/2e45540b-942e-4bbc-a04d-7e8eedaa5764

**Comment by Rakha112** [comment]
Here's a Snack you can try https://snack.expo.dev/@rakha112/drawer-bottom-tabs.
I will close this issue, but if you still have the bug, feel free to reopen this issue or create a new one.
Thank you
